# Site settings
title: Davide Papazzoni
email: itspapaz94@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Page for Davide Papazzoni, freelance Graphic Designer and Illustrator"
keywords: "your keywords, separated by commas"
skills: "Graphic Artist - Illustrator"
meta_author: Davide Papazzoni

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FF7F50 #FFBF00
  primary-rgb: "255,191,0" #"255,191,0"
  secondary: FFBF00 #FFBF00
  secondary-dark: FFBF00 #FFBF00

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/itsPapaz
  - title: facebook
    url: https://www.facebook.com/Paperaz
  - title: instagram
    url: https://www.instagram.com/itspapaz/
  - title: tumblr
    url: https://www.tumblr.com/blog/itspapaz94
  - title: github
    url: https://github.com/itsPapaz

# Postal address (add as many lines as necessary)
address:
  - line: Modena
  - line: Italy

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
